# 03-programs.conf — program variables (terminal, file manager, menu, pywal)
# Sourced from ~/.config/hypr/hyprland.conf. Do not source this file directly.

# See https://wiki.hyprland.org/Configuring/Keywords/

# Set programs that you use
$terminal = kitty
$fileManager = kitty -e yazi
$menu = rofi -show drun -config ~/.config/rofi/colors-rofi.rasi

# Set Pywal commands
$p1 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/blade_runner.png
$p2 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/mclaren.png
$p3 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/jig_jig.png
$p4 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/club.png
$p5 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/cyber_car.png
$p6 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/japan.png
$p7 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/street.png
$p8 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/alpine.png
$p9 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/neon-porsche.png
$p0 = /home/chris/.local/bin/wal-hypr.sh /home/chris/pics/wallpapers/liquid.png
