# BEGIN WAL
[colors.primary]
background = '#0e0915'
foreground = '#c2c1c4'

[colors.cursor]
text   = '#0e0915' # Apply background color to color of text inside cursor
cursor = '#c2c1c4' # Apply foreground color to color of cursor

[colors.vi_mode_cursor]
text    = '#0e0915' # Same as above
cursor  = '#c2c1c4'

[colors.search.matches]
foreground = '#0e0915' # Same as above
background = '#c2c1c4' # Apply bright/white color to bg color of matching search

[colors.search.focused_match]
foreground = 'CellBackground'
background = 'CellForeground'

[colors.line_indicator]
foreground = 'None'
background = 'None'

[colors.footer_bar]
foreground = '#61586c'
background = '#c2c1c4'

[colors.selection]
text       = 'CellBackground'
background = 'CellForeground'

[colors.normal]
black   = '#0e0915'
red     = '#7C8C6D'
green   = '#3353A6'
yellow  = '#C45BAF'
blue    = '#65A1D3'
magenta = '#BDA7C5'
cyan    = '#A7D4E9'
white   = '#c2c1c4'

[colors.bright]
black   = '#61586c'
red     = '#7C8C6D'
green   = '#3353A6'
yellow  = '#C45BAF'
blue    = '#65A1D3'
magenta = '#BDA7C5'
cyan    = '#A7D4E9'
white   = '#c2c1c4'

[font]
size = 12.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
# END WAL
